### ISSUE TITLE
Mobile Safari - input border highlight disappears on focus

### ISSUE THREAD

**Issue by methodbox** [methodbox/fetchDNS#3]
Creating for documentation purposes; first known bug.

Due to some specific styling requirements of mobile Safari on iOS (any version), the border highlight on the input for the domain field will not display unless a fully-qualified `border-bottom` CSS value is used. Example shown below.

This is fixed by this: https://github.com/methodbox/fetchDNS/commit/4815d41c939f17d1bf5dc60f5f7f8bb71ae92819

This is resolved in the live app by this: https://github.com/methodbox/fetchDNS/commit/bfd11ea79505e337256cc1f17788db019be09ea2

Faulty code:

```css
//  src/styles/Dns.css

input.valid:not([type]),
input.valid:not([type]):focus,
input.valid[type='text']:not(.browser-default),
input.valid[type='text']:not(.browser-default):focus,
input.valid[type='password']:not(.browser-default),
input.valid[type='password']:not(.browser-default):focus,
input.valid[type='email']:not(.browser-default),
input.valid[type='email']:not(.browser-default):focus,
input.valid[type='url']:not(.browser-default),
input.valid[type='url']:not(.browser-default):focus,
input.valid[type='time']:not(.browser-default),
input.valid[type='time']:not(.browser-default):focus,
input.valid[type='date']:not(.browser-default),
input.valid[type='date']:not(.browser-default):focus,
input.valid[type='datetime']:not(.browser-default),
input.valid[type='datetime']:not(.browser-default):focus,
input.valid[type='datetime-local']:not(.browser-default),
input.valid[type='datetime-local']:not(.browser-default):focus,
input.valid[type='tel']:not(.browser-default),
input.valid[type='tel']:not(.browser-default):focus,
input.valid[type='number']:not(.browser-default),
input.valid[type='number']:not(.browser-default):focus,
input.valid[type='search']:not(.browser-default),
input.valid[type='search']:not(.browser-default):focus,
textarea.materialize-textarea.valid,
textarea.materialize-textarea.valid:focus,
.select-wrapper.valid > input.select-dropdown {
  border-bottom: #9b69ff !important;    //   The issue exists here.
  box-shadow: 0 1px 0 0 #9b69ff !important;
}

input:not([type]):focus:not([readonly]),
input[type='text']:not(.browser-default):focus:not([readonly]),
input[type='password']:not(.browser-default):focus:not([readonly]),
input[type='email']:not(.browser-default):focus:not([readonly]),
input[type='url']:not(.browser-default):focus:not([readonly]),
input[type='time']:not(.browser-default):focus:not([readonly]),
input[type='date']:not(.browser-default):focus:not([readonly]),
input[type='datetime']:not(.browser-default):focus:not([readonly]),
input[type='datetime-local']:not(.browser-default):focus:not([readonly]),
input[type='tel']:not(.browser-default):focus:not([readonly]),
input[type='number']:not(.browser-default):focus:not([readonly]),
input[type='search']:not(.browser-default):focus:not([readonly]),
textarea.materialize-textarea:focus:not([readonly]) {
  border-bottom: #5e20d8 !important;    //   The issue exists here.
  box-shadow: 0 1px 0 0 #5e20d8 !important;
}
```

Solution:

```css 
border-bottom: 1px solid #5e20d8 !important;
```
